run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - bin
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck      # 检查错误处理
    - gosimple      # 简化代码建议
    - govet         # Go vet检查
    - ineffassign   # 检查无效赋值
    - staticcheck   # 静态分析
    - unused        # 检查未使用的代码
    - gofmt         # 格式化检查
    - goimports     # import顺序
    - misspell      # 拼写检查
    - goconst       # 常量检查
    - gosec         # 安全检查
    - bodyclose     # HTTP body关闭检查
    - noctx         # context检查
    - rowserrcheck  # SQL rows错误检查
    - sqlclosecheck # SQL关闭检查
  disable:
    - typecheck     # 类型检查（由go build处理）

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gofmt:
    simplify: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  gosec:
    excludes:
      - G404  # 使用弱随机数生成器
  
  staticcheck:
    go: "1.21"

issues:
  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    # 排除生成代码
    - path: internal/models
      linters:
        - unused
  
  max-issues-per-linter: 0
  max-same-issues: 0
